### ISSUE TITLE
[GradeManagment] Insertion of decimal values

### ISSUE THREAD

**Issue by Filmaluco** [Filmaluco/J-Viste-A-Minha-M-dia-#16]
**Describe the bug**
The grade input system doen't accept values with decimal places

**To Reproduce**
1. Go to BS-2 (grades fragment)
2. Click on any course
3. Try to input any value with decimal places (example 10.2)

**Expected behavior**
Being able to insert the value

**Smartphone (please complete the following information):**
 - Device: OnePlus 3T
 - Version of the code:  64a875c0a00e9463a505d839851e4010b578830e

**Additional context**
This is required for one of our goals of success

**Comment by ricardoslyox** [comment]
Fixed with commit #42d316d3ddb04b2ddd664e529b583945d1a5d88e
