### ISSUE TITLE
[UI] Grade value not centered 

### ISSUE THREAD

**Issue by Filmaluco** [Filmaluco/J-Viste-A-Minha-M-dia-#17]
**Describe the bug**
Display of information is not consistent, and/or as planned

**To Reproduce**
1. Go to BS-2 (grades fragment)
2. Click on any course
3. Insert a value like 9.5

**Expected behavior**
The number should be centered in the preview circle.

**Comment by ricardoslyox** [comment]
Fixed with commit #5f134bcbd1f2be3371b23ee8c3b5f40cca91bb3b
