### ISSUE TITLE
[UI] Information not explicited

### ISSUE THREAD

**Issue by Filmaluco** [Filmaluco/J-Viste-A-Minha-M-dia-#18]
There is currently no information on why there is no generation of the "preview of courses score to reach" on the predictions screen. 

I propose that there's at least a phrase explaining on why.
The best approach should even say what "Tags" are still required to generate the preview

**Comment by ricardoslyox** [comment]
Fixed in commit #bd3530a042f8d96688aba2926a484d52c0d5705c
