### ISSUE TITLE
Possible error found in Student.java

### ISSUE THREAD

**Issue by Vascoide** [Filmaluco/J-Viste-A-Minha-M-dia-#5]
`intendedAverage` and `predictionAverage` variables either are the same, or what they are isn't clear enough and I'd like to be clarified.

![image](https://user-images.githubusercontent.com/24484281/48971470-122fcc00-f012-11e8-82a4-cc2882a34d18.png)

**Comment by Filmaluco** [comment]
**intededAverage**, this is user/student inteded average. Simplifying this is the variable that stores the user/student setting.

*predictionAverage* is the user/student predicted average. Simplifying is the variable that holds the last calculated predicted average.
