### ISSUE TITLE
Wrong Class By Year

### ISSUE THREAD

**Issue by ricardoslyox** [Filmaluco/J-Viste-A-Minha-M-dia-#9]
**Describe the bug**
Class appearing at the wrong year

**To Reproduce**
1. Go to Notas
2. Click on 2º ano
3. Scroll down to 1 semestre
4. See error (ME)

**Screenshots**
<img width="320" alt="screenshot 2018-11-26 at 15 49 47" src="https://user-images.githubusercontent.com/33632491/49025221-146d6400-f193-11e8-91d7-5f54b8b06589.png">

**Comment by Vascoide** [comment]
Donezo on the master branch.
